CREATE TABLE professionals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    birth_date DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    department_id BIGINT,
    position_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_professionals_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT fk_professionals_department
        FOREIGN KEY (department_id) REFERENCES departments (id),
    CONSTRAINT fk_professionals_position
        FOREIGN KEY (position_id) REFERENCES positions (id)
);
