CREATE TABLE contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professional_id BIGINT NOT NULL,
    type VARCHAR(30) NOT NULL,
    value VARCHAR(255) NOT NULL,
    label VARCHAR(80),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_contacts_type CHECK (type IN ('EMAIL', 'PHONE', 'MOBILE', 'OTHER')),
    CONSTRAINT fk_contacts_professional
        FOREIGN KEY (professional_id) REFERENCES professionals (id) ON DELETE CASCADE
);
